# Generated by Django 5.2.6 on 2025-10-16 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("system", "系统日志"),
                            ("security", "安全日志"),
                            ("operation", "操作日志"),
                            ("performance", "性能日志"),
                            ("application", "应用日志"),
                        ],
                        max_length=20,
                        verbose_name="日志类型",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "调试"),
                            ("INFO", "信息"),
                            ("WARNING", "警告"),
                            ("ERROR", "错误"),
                            ("CRITICAL", "严重"),
                        ],
                        max_length=10,
                        verbose_name="日志级别",
                    ),
                ),
                (
                    "source_module",
                    models.CharField(max_length=100, verbose_name="来源模块"),
                ),
                ("message", models.TextField(verbose_name="消息内容")),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="详细信息"),
                ),
                (
                    "user",
                    models.CharField(
                        default="system", max_length=100, verbose_name="用户"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BackupFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="备份名称")),
                ("file_path", models.CharField(max_length=500, verbose_name="文件路径")),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "完整备份"),
                            ("incremental", "增量备份"),
                            ("differential", "差异备份"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="备份类型",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "已完成"),
                            ("running", "备份中"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="备份状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("description", models.TextField(blank=True, verbose_name="备份描述")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
            ],
            options={
                "verbose_name": "备份文件",
                "verbose_name_plural": "备份文件",
                "db_table": "backup_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_backup_enabled",
                    models.BooleanField(default=True, verbose_name="启用自动备份"),
                ),
                (
                    "backup_frequency",
                    models.CharField(
                        default="daily", max_length=20, verbose_name="备份频率"
                    ),
                ),
                (
                    "max_backup_files",
                    models.IntegerField(default=30, verbose_name="保留备份数量"),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "完整备份"),
                            ("incremental", "增量备份"),
                            ("differential", "差异备份"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="备份类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "备份设置",
                "verbose_name_plural": "备份设置",
                "db_table": "backup_settings",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="部门名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="部门描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="邮件通知"),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="短信通知"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, verbose_name="推送通知"),
                ),
                (
                    "webhook_enabled",
                    models.BooleanField(default=False, verbose_name="Webhook通知"),
                ),
                (
                    "smtp_server",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SMTP服务器"
                    ),
                ),
                ("smtp_port", models.IntegerField(default=587, verbose_name="SMTP端口")),
                (
                    "smtp_username",
                    models.CharField(blank=True, max_length=200, verbose_name="发件人邮箱"),
                ),
                (
                    "smtp_password",
                    models.CharField(blank=True, max_length=200, verbose_name="SMTP密码"),
                ),
                (
                    "sender_name",
                    models.CharField(
                        default="系统通知", max_length=100, verbose_name="发件人名称"
                    ),
                ),
                (
                    "system_error_notify",
                    models.BooleanField(default=True, verbose_name="系统错误"),
                ),
                (
                    "security_alert_notify",
                    models.BooleanField(default=True, verbose_name="安全警报"),
                ),
                (
                    "task_complete_notify",
                    models.BooleanField(default=True, verbose_name="备份完成"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "通知设置",
                "verbose_name_plural": "通知设置",
            },
        ),
        migrations.CreateModel(
            name="PerformanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_retention_days",
                    models.IntegerField(default=90, verbose_name="数据保留时间(天)"),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "调试"),
                            ("INFO", "信息"),
                            ("WARNING", "警告"),
                            ("ERROR", "错误"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="日志级别",
                    ),
                ),
                (
                    "auto_backup_enabled",
                    models.BooleanField(default=False, verbose_name="启用自动备份"),
                ),
                (
                    "backup_interval",
                    models.CharField(
                        choices=[("daily", "每天"), ("weekly", "每周"), ("monthly", "每月")],
                        default="daily",
                        max_length=20,
                        verbose_name="备份间隔",
                    ),
                ),
                (
                    "monitoring_interval",
                    models.IntegerField(default=60, verbose_name="监控数据采样间隔(秒)"),
                ),
                (
                    "enable_data_compression",
                    models.BooleanField(default=True, verbose_name="启用数据缓存"),
                ),
                (
                    "enable_cache_optimization",
                    models.BooleanField(default=False, verbose_name="启用数据压缩缓存"),
                ),
                (
                    "enable_realtime_monitoring",
                    models.BooleanField(default=True, verbose_name="启用实时监控"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "性能设置",
                "verbose_name_plural": "性能设置",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("editor", "编辑员"),
                            ("viewer", "观察者"),
                            ("auditor", "审计员"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="角色名称",
                    ),
                ),
                ("display_name", models.CharField(max_length=100, verbose_name="显示名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="角色描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_timeout",
                    models.IntegerField(default=60, verbose_name="会话超时时间(分钟)"),
                ),
                (
                    "password_strength",
                    models.CharField(
                        choices=[("low", "低强度"), ("medium", "中等强度"), ("high", "高强度")],
                        default="medium",
                        max_length=20,
                        verbose_name="密码强度",
                    ),
                ),
                (
                    "max_login_attempts",
                    models.IntegerField(default=5, verbose_name="最大登录尝试次数"),
                ),
                (
                    "account_lockout_time",
                    models.IntegerField(default=30, verbose_name="账户锁定时间(分钟)"),
                ),
                (
                    "two_factor_auth",
                    models.BooleanField(default=False, verbose_name="启用双因素认证"),
                ),
                (
                    "force_password_change",
                    models.BooleanField(default=True, verbose_name="强制定期修改密码"),
                ),
                (
                    "audit_logging",
                    models.BooleanField(default=True, verbose_name="启用审计日志"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "安全设置",
                "verbose_name_plural": "安全设置",
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="设置键"),
                ),
                ("value", models.TextField(verbose_name="设置值")),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("general", "常规设置"),
                            ("security", "安全设置"),
                            ("notification", "通知设置"),
                            ("performance", "性能设置"),
                        ],
                        max_length=20,
                        verbose_name="设置类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="设置描述"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统设置",
                "verbose_name_plural": "系统设置",
                "ordering": ["setting_type", "key"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("export", "导出"),
                            ("import", "导入"),
                            ("download", "下载"),
                            ("backup", "备份"),
                            ("restore", "恢复"),
                            ("config", "系统设置"),
                            ("user_mgmt", "用户管理"),
                            ("robot_mgmt", "机器人配置"),
                            ("task_mgmt", "任务调度"),
                            ("file_mgmt", "录像文件"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "operation_target",
                    models.CharField(max_length=100, verbose_name="操作对象"),
                ),
                ("operation_detail", models.TextField(verbose_name="操作详情")),
                (
                    "operator_name",
                    models.CharField(max_length=100, verbose_name="操作人姓名"),
                ),
                ("operator_ip", models.GenericIPAddressField(verbose_name="操作IP地址")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("warning", "警告"),
                        ],
                        default="success",
                        max_length=20,
                        verbose_name="操作结果",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "operation_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                ("duration", models.FloatField(default=0.0, verbose_name="操作耗时(秒)")),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="用户代理"),
                ),
                (
                    "request_data",
                    models.JSONField(blank=True, null=True, verbose_name="请求数据"),
                ),
                (
                    "response_data",
                    models.JSONField(blank=True, null=True, verbose_name="响应数据"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("real_name", models.CharField(max_length=100, verbose_name="真实姓名")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "未激活"),
                            ("locked", "已锁定"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="最后登录IP"
                    ),
                ),
                ("login_count", models.IntegerField(default=0, verbose_name="登录次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ops.department",
                        verbose_name="部门",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ops.role",
                        verbose_name="角色",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
                "ordering": ["-created_at"],
            },
        ),
    ]
