# Generated by Django 5.2.5 on 2025-10-23 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='狗名称')),
                ('breed', models.CharField(blank=True, max_length=50, null=True, verbose_name='品种')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('maintenance', '维护中')], default='active', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='位置')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '虚拟狗',
                'verbose_name_plural': '虚拟狗',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='摄像头名称')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.IntegerField(default=554, verbose_name='端口')),
                ('rtsp_url', models.URLField(verbose_name='RTSP流地址')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '故障')], default='offline', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='位置')),
                ('resolution', models.CharField(default='1920x1080', max_length=20, verbose_name='分辨率')),
                ('fps', models.IntegerField(default=25, verbose_name='帧率')),
                ('is_recording', models.BooleanField(default=False, verbose_name='是否录制')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='ops.dog', verbose_name='所属狗')),
            ],
            options={
                'verbose_name': '摄像头',
                'verbose_name_plural': '摄像头',
                'ordering': ['dog', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('smoking', '吸烟检测'), ('phone', '电话检测'), ('fire', '火灾检测'), ('stranger', '陌生人检测'), ('fighting', '打架斗殴')], max_length=20, verbose_name='事件类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='截图路径')),
                ('video_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='视频路径')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('detection_data', models.JSONField(blank=True, null=True, verbose_name='检测数据')),
                ('detected_at', models.DateTimeField(verbose_name='检测时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='处理备注')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.camera', verbose_name='摄像头')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.dog', verbose_name='所属狗')),
            ],
            options={
                'verbose_name': '报警事件',
                'verbose_name_plural': '报警事件',
                'ordering': ['-detected_at'],
            },
        ),
    ]
