# Generated by Django 5.2.4 on 2025-10-29 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0003_add_face_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camera",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "摄像头",
                "verbose_name_plural": "摄像头",
            },
        ),
        migrations.AlterModelOptions(
            name="dog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "虚拟犬",
                "verbose_name_plural": "虚拟犬",
            },
        ),
        migrations.RenameField(
            model_name="alarmevent",
            old_name="resolution_notes",
            new_name="handle_note",
        ),
        migrations.RenameField(
            model_name="alarmevent",
            old_name="handled_by",
            new_name="handler",
        ),
        migrations.RenameIndex(
            model_name="facerecord",
            new_name="ops_facerec_employe_d261ed_idx",
            old_name="ops_facerec_employe_idx",
        ),
        migrations.RenameIndex(
            model_name="facerecord",
            new_name="ops_facerec_status_a43271_idx",
            old_name="ops_facerec_status_idx",
        ),
        migrations.RenameIndex(
            model_name="facerecord",
            new_name="ops_facerec_created_6b2f34_idx",
            old_name="ops_facerec_created_idx",
        ),
        migrations.RemoveField(
            model_name="alarmevent",
            name="resolved_at",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="is_recording",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="port",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="breed",
        ),
        migrations.AddField(
            model_name="alarmevent",
            name="handled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
        ),
        migrations.AddField(
            model_name="alarmevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="camera",
            name="camera_id",
            field=models.CharField(
                default="CAM_DEFAULT",
                max_length=50,
                unique=True,
                verbose_name="摄像头编号",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="dog",
            name="dog_id",
            field=models.CharField(
                default="DOG_DEFAULT",
                max_length=50,
                unique=True,
                verbose_name="虚拟犬编号",
            ),
        ),
        migrations.AlterField(
            model_name="alarmevent",
            name="camera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_events",
                to="ops.camera",
                verbose_name="触发摄像头",
            ),
        ),
        migrations.AlterField(
            model_name="alarmevent",
            name="detection_data",
            field=models.JSONField(blank=True, null=True, verbose_name="检测详细数据"),
        ),
        migrations.AlterField(
            model_name="alarmevent",
            name="dog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_events",
                to="ops.dog",
                verbose_name="所属虚拟犬",
            ),
        ),
        migrations.AlterField(
            model_name="alarmevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("smoking", "吸烟检测"),
                    ("phone", "打电话检测"),
                    ("fire", "火灾检测"),
                    ("stranger", "陌生人检测"),
                    ("fighting", "打架斗殴检测"),
                    ("rubbish", "垃圾检测"),
                    ("crossover", "翻越检测"),
                ],
                max_length=20,
                verbose_name="事件类型",
            ),
        ),
        migrations.AlterField(
            model_name="alarmevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("processing", "处理中"),
                    ("resolved", "已解决"),
                    ("ignored", "已忽略"),
                ],
                default="pending",
                max_length=20,
                verbose_name="处理状态",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="dog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cameras",
                to="ops.dog",
                verbose_name="所属虚拟犬",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="location",
            field=models.CharField(
                default="unknown", max_length=200, verbose_name="安装位置"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="camera",
            name="rtsp_url",
            field=models.CharField(max_length=500, verbose_name="RTSP流地址"),
        ),
        migrations.AlterField(
            model_name="dog",
            name="location",
            field=models.CharField(
                default="unknown", max_length=200, verbose_name="巡逻区域"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dog",
            name="name",
            field=models.CharField(max_length=100, verbose_name="虚拟犬名称"),
        ),
        migrations.AlterField(
            model_name="dog",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "在线"),
                    ("offline", "离线"),
                    ("maintenance", "维护中"),
                ],
                default="offline",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddIndex(
            model_name="alarmevent",
            index=models.Index(
                fields=["-detected_at"], name="ops_alarmev_detecte_f12fe9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alarmevent",
            index=models.Index(
                fields=["event_type", "status"], name="ops_alarmev_event_t_f24c0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alarmevent",
            index=models.Index(
                fields=["camera", "-detected_at"], name="ops_alarmev_camera__f69e17_idx"
            ),
        ),
    ]
